### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by zelongg** [studychen/SeeNewsV2#1]
01-23 05:17:31.921 23475-23475/? E/JPush: [JPushGlobal] Get sdk version fail![获取sdk版本失败!]
01-23 05:17:31.931 23475-23475/? E/JPush: [JPushGlobal] JPush .so file do not match JPush .jar file in the project, Failed to init JPush
01-23 05:17:31.941 23475-23475/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.studychen.seenews, PID: 23475
                                                   java.lang.NoClassDefFoundError: cn/jpush/android/service/PushProtocol
                                                       at cn.jpush.android.b.a(Unknown Source)
                                                       at cn.jpush.android.b.a(Unknown Source)
                                                       at cn.jpush.android.service.PushReceiver.onReceive(Unknown Source)
                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2419)
                                                       at android.app.ActivityThread.access$1700(ActivityThread.java:135)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by zelongg** [comment]
解决了，在以下路径SeeNewsV2/app/src/main/jniLibs，新建了jniLibs目录。

把以下目录的文件

```
/Users/gongzelong/Android/githubreposample/SeeNewsV2/app/libs/arm64-v8a
/Users/gongzelong/Android/githubreposample/SeeNewsV2/app/libs/armeabi
/Users/gongzelong/Android/githubreposample/SeeNewsV2/app/libs/armeabi-v7a
```

复制拷贝到以下目录

```
/Users/gongzelong/Android/githubreposample/SeeNewsV2/app/src/main/jniLibs/arm64-v8a
/Users/gongzelong/Android/githubreposample/SeeNewsV2/app/src/main/jniLibs/armeabi
/Users/gongzelong/Android/githubreposample/SeeNewsV2/app/src/main/jniLibs/armeabi-v7a
```

**Comment by gongzelong0718** [comment]
Marked
